filepath: examples/bvh/fair1/wave_hello.bvh
start_frame_idx: 450
end_frame_idx: 530
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +z
