filepath: examples/bvh/fair1/zombie.bvh
start_frame_idx: 40
end_frame_idx: 100
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +z
