spring:
  application:
    name: auth-service
  cloud:
    config:
      name: deploy
      profile: auth
  config:
    import: "optional:configserver:http://k9d106.p.ssafy.io:9900/"

eureka:
  client:
    service-url:
      defaultZone: http://k9d106.p.ssafy.io:8761/eureka/
  instance:
    hostname: k9d106.p.ssafy.io

encrypt:
  key: ${ENCRYPT_KEY}