spring:
  application:
    name: draw-service
  cloud:
    config:
      name: local
      profile: draw3
  config:
    import: "optional:configserver:http://k9d106.p.ssafy.io:9900/"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

encrypt:
  key: ${ENCRYPT_KEY}